### ISSUE TITLE
Receiver Repo Lookup doesn't handle multiple repos

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-x-receiver#15]
https://github.com/topcoder-platform/topcoder-x-receiver/blob/be622f04597a76aeba11b7ffb58b645553265590/routes/middlewares/SecurityChecker.js#L20

For topcoder-platform/community-app, there were 3 entries in the TCX dynamo DB for the same git repo. The linked line above was pulling the first it found, checking the secret, and saying it's an invalid request.

Two things should happen:
1. That line should pull all repos that match the URL and check the secret against each one
2. We should consider not allowing multiple additions of the same repo? Maybe owner should be an array of people? Not sure what's best here.

**Comment by jmgasper** [comment]
@rootelement - We can definitely add a check of all secrets.  We can likely block additions of the same repo at the UI level.

**Comment by jmgasper** [comment]
Moved to the UI issues, which is where I like to launch from:  https://github.com/topcoder-platform/topcoder-x-ui/issues/279
