### ISSUE TITLE
[$50] Support new TC Event format standard 

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-x-receiver#2]
we have a new standard for Kafka events that we'll need to convert TC-X events to for compliance

**Comment by jmgasper** [comment]
@cwdcwd  - Is this new standard documented somewhere?

**Comment by cwdcwd** [comment]
[CORE-TopcoderEventBus-060718-1930.pdf](https://github.com/topcoder-platform/topcoder-x-receiver/files/2172224/CORE-TopcoderEventBus-060718-1930.pdf)
